app:
  name: cunsumer-template
  port: 8080
  version: 1.0
  env: dev
  chunk-size: 2
  chunk-size-reader: 3

log:
  env: local
  level: "debug"

kafka_producer:
  sasl:
    enable: true
    mechanism: "PLAIN"
  tls:
    enable: false
  producer:
    partitioner: "roundrobin"
  topics:
    topic: "product"

secrets:
  cloud-sql-gormhost: 127.0.0.1
  cloud-sql-port: "3306"
  cloud-sql-username: "root"
  cloud-sql-password: "0872772514Za"
  cloud-sql-dbname: "acn_database"
  aws:
    access-key:
    secret-key:
    S3:
      bucket-name:
      bucket-arn:
      region: "ap-southeast-1"